import { ZikrItem } from "../types";

export const AZKAAR: ZikrItem[] = [
  {
    id: 1,
    arabic: "سُبْحَانَ اللهِ وَبِحَمْدِهِ",
    transliteration: "SubhanAllahi wa bihamdihi",
    translation: "Glory and praise be to Allah",
    reference: "Sahih Bukhari",
    recommendedCount: 100,
    category: "general",
    isSunnah: true,
  },
  {
    id: 2,
    arabic: "سُبْحَانَ اللهِ، وَالْحَمْدُ لِلَّهِ، وَلَا إِلَهَ إِلَّا اللهُ، وَاللهُ أَكْبَرُ",
    transliteration: "SubhanAllahi walhamdulillahi wala ilaha illAllahu wallahu Akbar",
    translation: "Glory to Allah, praise to Allah, none has the right to be worshipped but Allah, Allah is greatest",
    reference: "Sunan an-Nasai",
    recommendedCount: 33,
    category: "afterSalah",
    isSunnah: true,
  },
  {
    id: 3,
    arabic: "أَسْتَغْفِرُ اللهَ",
    transliteration: "Astaghfirullah",
    translation: "I seek forgiveness from Allah",
    reference: "Sahih Muslim",
    recommendedCount: 100,
    category: "general",
    isSunnah: true,
  },
  {
    id: 4,
    arabic: "لَا إِلَهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
    transliteration: "La ilaha illa Anta subhanaka inni kuntu minaz-zalimin",
    translation: "None has the right to be worshipped but You, glory to You, I was among the wrongdoers",
    reference: "Surah Al-Anbiya 21:87",
    recommendedCount: 7,
    category: "evening",
    isSunnah: false,
  },
  {
    id: 5,
    arabic: "اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ",
    transliteration: "Allahumma salli 'ala Muhammad",
    translation: "O Allah, send blessings upon Muhammad",
    reference: "Sahih Bukhari",
    recommendedCount: 10,
    category: "afterSalah",
    isSunnah: true,
  },
  {
    id: 6,
    arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transliteration: "La hawla wa la quwwata illa billah",
    translation: "There is no power nor strength except with Allah",
    reference: "Sahih Bukhari",
    recommendedCount: 33,
    category: "afterSalah",
    isSunnah: true,
  },
];

export const ZIKR_CATEGORIES: { key: string; label: string }[] = [
  { key: "morning", label: "Morning" },
  { key: "evening", label: "Evening" },
  { key: "afterSalah", label: "After Salah" },
  { key: "general", label: "General" },
  { key: "favorites", label: "Favorites" },
];